### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by jbouwh** [paprins/omnik-data-logger#1]
I found out that there is a syntax error in client.py:
File:
https://github.com/paprins/omnik-data-logger/blob/master/omnik/client.py
With pip3 install this file is located here at my distribution:
/usr/local/lib/python3.7/dist-packages/omnik/client.py

Line: 55

is:  
  url = '{self.base_url}/plant/list'
should be:
  url = f'{self.base_url}/plant/list'

After this patch the client works and submists the data to pvoutput.org.

**Comment by paprins** [comment]
Hi, must have been a glitch ... my bad, you're right. Will have a look at your PR and merge it.

**Comment by paprins** [comment]
Fixed issue ... keeping PR open for (future) Home Assistant compatibility.
